import '../styles/globals.css';
import '../styles/fonts.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from "@/containers/Header";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="font-poppins text-white bg-slate-950">
        <Header/>
        {children}
      </body>
    </html>
  )
}
